module.exports = {
    prefix: '',
    important: false,
    purge: false,
    separator: ':',
    theme: {
      colors: {
        color1: 'var(--1)',
        color2: 'var(--2)',
        color3: 'var(--3)',
        color4: 'var(--4)',
        color5: 'var(--5)',
        color6: 'var(--6)',
        color7: 'var(--7)',
        white: 'var(--white)',
        transparent: 'var(--transparent)',
      },
      spacing: {
        px: '1px',
        0: '0',
        1: '1px',
        2: '0.125rem',
        4: '0.25rem',
        6: '0.375rem',
        8: '0.5rem',
        10: '0.625rem',
        12: '0.75rem',
        16: '1rem',
        24: '1.5rem',
        32: '2rem',
        48: '3rem',
        64: '4rem',
        80: '5rem',
        '2per': '2%',
      },
      size: {
        auto: 'auto',
        '1/2': '50%',
        '1/3': '33.33333%',
        '2/3': '66.66667%',
        '1/4': '25%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.66667%',
        '5/6': '83.33333%',
        '1/10': '10%',
  
        0: '0',
        2: '0.125rem',
        6: '0.375rem',
        8: '0.5rem',
        10: '0.625rem',
        12: '0.75rem',
        16: '1rem',
        20: '1.25rem',
        24: '1.5rem',
        28: '1.75rem',
        30: '1.875rem',
        32: '2rem',
        36: '2.25rem',
        40: '2.5rem',
        48: '3rem',
        50: '3.125rem',
        52: '3.25rem',
        56: '3.5rem',
        60: '3.75rem',
        64: '4rem',
        80: '5rem',
        100: '6.25rem',
        128: '8rem',
        240: '15rem',
        272: '17rem',
        full: '100%',
        none: 'none',
        unset: 'unset',
      },
      screens: {
        md: { max: '1024px' },
        lg: { max: '1366px' },
        xl: { max: '1920px' },
      },
      fontSize: {
        base: '0.75rem',
        10: '0.625rem',
        12: '0.75rem',
        14: '0.875rem',
        16: '1rem',
        18: '1.125rem',
        24: '1.5rem',
      },
      lineHeight: {
        none: 1,
        tight: 1.25,
        snug: 1.375,
        normal: 1.5,
        relaxed: 1.625,
        loose: 2,
        14: '0.875rem',
        16: '1rem',
        18: '1.125rem',
        20: '1.25rem',
        22: '1.375rem',
        24: '1.5rem',
        26: '1.625rem',
        initial: 'initial',
      },
      textColor: (theme) => theme('colors'),
      background: (theme) => theme('colors'),
      fill: (theme) => theme('colors'),
      backgroundPosition: {
        bottom: 'bottom',
        center: 'center',
        left: 'left',
        'left-bottom': 'left bottom',
        'left-top': 'left top',
        right: 'right',
        'right-bottom': 'right bottom',
        'right-top': 'right top',
        top: 'top',
      },
      backgroundSize: {
        auto: 'auto',
        cover: 'cover',
        contain: 'contain',
      },
      borderWidth: {
        default: '0.0625rem',
        0: '0',
        1: '0.0625rem',
        2: '0.125rem',
        3: '0.1875rem',
        4: '0.25rem',
      },
      hoverDark: (theme) => ({
        ...theme('colors'),
        default: theme('colors.black', 'currentColor'),
      }),
      borderRadius: {
        none: '0',
        2: '0.125rem',
        3: '0.1875rem',
        4: '0.25rem',
        5: '0.3125rem',
        7: '0.4375rem',
        8: '0.5rem',
        10: '0.625rem',
        20: '1.25rem',
        full: '50%',
      },
      cursor: {
        auto: 'auto',
        default: 'default',
        pointer: 'pointer',
        wait: 'wait',
        move: 'move',
        'not-allowed': 'not-allowed',
      },
      width: (theme) => ({
        ...theme('size'),
        screen: '100vw',
      }),
      height: (theme) => ({
        ...theme('size'),
        screen: '100vh',
      }),
      minWidth: (theme) => ({
        ...theme('width'),
      }),
      minHeight: (theme) => ({
        ...theme('height'),
      }),
      maxWidth: (theme) => ({
        ...theme('width'),
      }),
      maxHeight: (theme) => ({
        ...theme('height'),
      }),
      padding: (theme) => theme('spacing'),
      margin: (theme) => ({ auto: 'auto', ...theme('spacing') }),
      negativeMargin: (theme) => theme('spacing'),
      objectPosition: {
        bottom: 'bottom',
        center: 'center',
        left: 'left',
        'left-bottom': 'left bottom',
        'left-top': 'left top',
        right: 'right',
        'right-bottom': 'right bottom',
        'right-top': 'right top',
        top: 'top',
      },
      boxShadow: {
        default: '0 0.0625rem 0.1875rem 0 rgba(0, 0, 0, .1), 0 0.0625rem 0.125rem 0 rgba(0, 0, 0, .06)',
        md: '0 0.25rem 0.375rem -0.0625rem rgba(0, 0, 0, .1), 0 0.125rem 0.25rem -0.0625rem rgba(0, 0, 0, .06)',
        lg: '0 0.625rem 0.9375rem -0.1875rem rgba(0, 0, 0, .1), 0 0.25rem 0.375rem -0.125rem rgba(0, 0, 0, .05)',
        xl: '0 1.25rem 1.5625rem -0.3125rem rgba(0, 0, 0, .1), 0 0.625rem 0.625rem -0.3125rem rgba(0, 0, 0, .04)',
        '2xl': '0 1.5625rem 3.125rem -0.75rem rgba(0, 0, 0, .25)',
        inner: 'inset 0 0.125rem 0.25rem 0 rgba(0,0,0,0.06)',
        outline: '0 0 0 0.1875rem rgba(66,153,225,0.5)',
        none: 'none',
      },
      zIndex: {
        auto: 'auto',
        0: 0,
        5: 5,
        10: 10,
        15: 15,
        20: 20,
        25: 25,
        30: 30,
        35: 35,
        40: 40,
        45: 45,
        50: 50,
        full: 100,
      },
      opacity: {
        0: '0',
        4: '0.04',
        8: '0.08',
        15: '0.15',
        25: '0.25',
        30: '0.3',
        50: '0.5',
        75: '0.75',
        80: '0.8',
        100: '1',
      },
  
      stroke: {
        current: 'currentColor',
      },
      flex: {
        1: '1 1 0%',
        auto: '1 1 auto',
        initial: '0 1 auto',
        none: 'none',
      },
      flexGrow: {
        0: 0,
        default: 1,
      },
      flexShrink: {
        0: 0,
        default: 1,
      },
      listStyleType: {
        none: 'none',
        disc: 'disc',
        decimal: 'decimal',
      },
      inset: (theme) => ({
        ...theme('spacing'),
        0: 0,
        auto: 'auto',
      }),
      container: {},
    },
    variants: [],
    corePlugins: {
      float: false,
      objectFit: false,
      objectPosition: false,
      gap: false,
      container: false,
      accessibility: false,
      alignContent: false,
      animation: false,
      appearance: false,
      backgroundAttachment: false,
      backgroundClip: false,
      backgroundImage: false,
      backgroundOpacity: false,
      backgroundPosition: false,
      backgroundRepeat: false,
      backgroundSize: false,
      borderCollapse: false,
      borderOpacity: false,
      boxSizing: false,
      clear: false,
      divideColor: false,
      divideOpacity: false,
      divideStyle: false,
      divideWidth: false,
      fontFamily: false,
      fontSmoothing: false,
      fontVariantNumeric: false,
      gradientColorStops: false,
      gridAutoColumns: false,
      gridAutoFlow: false,
      gridAutoRows: false,
      gridColumn: false,
      gridColumnEnd: false,
      gridColumnStart: false,
      gridRow: false,
      gridRowEnd: false,
      gridRowStart: false,
      gridTemplateColumns: false,
      gridTemplateRows: false,
      letterSpacing: false,
      listStylePosition: false,
      order: false,
      placeContent: false,
      placeholderColor: false,
      placeholderOpacity: false,
      placeItems: false,
      placeSelf: false,
    },
  
    plugins: [],
  }
  